<?php
// troubleshoot.php - Place this in the root of your project

ini_set('display_errors', 1);
error_reporting(E_ALL);

echo "<h1>Troubleshooting Script</h1>";

$autoloader_path = __DIR__ . '/vendor/autoload.php';
echo "<p>Checking for autoloader at: <code>" . htmlspecialchars($autoloader_path) . "</code></p>";

if (file_exists($autoloader_path)) {
    echo "<p style='color:green;'>Autoloader file found.</p>";

    if (is_readable($autoloader_path)) {
        echo "<p style='color:green;'>Autoloader file is readable.</p>";
        
        try {
            require_once $autoloader_path;
            echo "<p style='color:green;'>Autoloader included successfully.</p>";

            if (class_exists('FPDF')) {
                echo "<p style='color:green; font-weight:bold;'>SUCCESS: The FPDF class is now available!</p>";
                echo "<p>The original error should be resolved. Please try downloading the PDF again. If it still fails, it might be a server cache (like OPcache). Try restarting your web server process.</p>";
            } else {
                echo "<p style='color:red; font-weight:bold;'>ERROR: The FPDF class was NOT found after including the autoloader.</p>";
                echo "<p>This suggests an issue with the composer installation or the autoloader files. Please try running `composer dump-autoload` and check for any errors.</p>";
            }
        } catch (Exception $e) {
            echo "<p style='color:red; font-weight:bold;'>ERROR: An exception occurred while including the autoloader:</p>";
            echo "<pre>" . htmlspecialchars($e->getMessage()) . "</pre>";
        }

    } else {
        echo "<p style='color:red; font-weight:bold;'>ERROR: Autoloader file exists but is NOT readable by the web server.</p>";
        echo "<p>This is a file permission issue. The user running the web server (e.g., 'www-data' or 'nchdesi') does not have permission to read the files generated by the 'root' user. Please contact your hosting provider to fix file ownership.</p>";
    }

} else {
    echo "<p style='color:red; font-weight:bold;'>ERROR: Autoloader file does NOT exist.</p>";
    echo "<p>This confirms that `composer install` or `composer update` did not complete successfully. The `vendor` directory is missing or incomplete.</p>";
}
?>